export enum METHOD_RESPONSE {
  METHOD_NOT_FOUND = 'Method not found',
  METHOD_NOT_FOUND_BY_ID = 'Method not found by id',
  METHOD_NOT_FOUND_BY_USER = 'Method not found by user',
  METHOD_NOT_FOUND_BY_USER_AND_ID = 'Method not found by user and id',
  METHOD_NOT_FOUND_BY_TEAM_AND_ID = 'Method not found by team and id',
  METHOD_NOT_SAVED = 'Method not saved',
  METHOD_NOT_DELETED = 'Method not deleted',
  METHOD_NOT_UPDATED = 'Method not updated',
  METHOD_INVOCATION_NOT_FOUND = 'Invocation not found',
  METHODS_NOT_DELETED = 'Error when try to remove methods',
  METHOD_DELETED = 'Method deleted',
  METHOD_UPDATED = 'Method updated',
  METHOD_FOUND = 'Method found',
  METHOD_CREATED = 'Method created',
}
