entity: Environment
items:
  environment0:
    id: 'enviroment0'
    name: 'enviroment0'
    value: 'enviroment0'
    user: '@user0'
    collection: '@collection0'

  environment1:
    id: 'enviroment1'
    name: 'enviroment1'
    value: 'enviroment1'
    user: '@user1'
    collection: '@collection1'
