export enum INVOCATION_RESPONSE {
  Invocation_NOT_FOUND = 'Invocation not found',
  Invocation_NOT_FOUND_BY_ID = 'Invocation not found by id',
  Invocation_NOT_FOUND_BY_USER = 'Invocation not found by user',
  Invocation_NOT_FOUND_BY_USER_AND_ID = 'Invocation not found by user and id',
  Invocation_NOT_SAVE = 'Invocation not saved',
  Invocation_NOT_DELETED = 'Invocation not deleted',
  Invocation_NOT_UPDATED = 'Invocation not updated',
  INVOCATION_FOLDER_NOT_EXISTS = 'Folder not exists or its not yours',
  INVOCATION_FAIL_GENERATE_METHODS_WITH_CONTRACT_ID = 'It was not possible to generate new methods with the assigned contract id.',
  INVOCATION_FAIL_RUN_INVOCATION = 'It was not possible to run the invocation',
  INVOCATION_FAIL_WITH_NEW_CONTRACT_AND_NEW_METHOD = 'You cannot set a new method and new contract at the same time',
  INVOCATION_FAIL_SELECTING_METHOD_WITHOUT_CONTRACT = 'You cannot choose a method without having a loaded contract',
  INVOCATION_FAILED_TO_RUN_WITHOUT_KEYS_OR_SELECTED_METHOD = 'It was not possible to run the invocation. Check if you have selected method or keys',
}
