export enum FOLDER_RESPONSE {
  FOLDER_NOT_FOUND = 'Folder not found',
  FOLDERS_NOT_FOUND = 'Folders not found',
  FOLDER_NOT_FOUND_BY_USER_ID = 'Folder not found by user id',
  FOLDER_NOT_FOUND_BY_TEAM_ID = 'Folder not found by team id',
  FOLDER_COLLECTION_NOT_FOUND = 'The collection does not exist',
  FOLDER_FAILED_SAVE = 'Could not save folder, please try again',
  FOLDER_FAILED_DELETED = 'Could not deleted folder, please try again',
  FOLDER_FAILED_UPDATED = 'Could not updated folder, please try again',
  FOLDER_CREATED = 'Folder created',
  FOLDER_FOUND = 'Folder found',
  INVOCATIONS_FOUND = 'Invocations found',
  FOLDER_UPDATED = 'Folder updated',
  FOLDER_DELETED = 'Folder deleted',
}
