export enum ServiceMessageFileUpload {
  BUCKET_CREATED = 'Bucket created',
  BUCKET_EXISTS = 'Bucket exists',
  BUCKET_CREATION_FAILED = 'Bucket creation failed',
  BUCKET_CHECK_FAILED = 'Bucket check failed',
  FILE_UPLOADED_SUCCESSFULLY = 'File uploaded successfully',
  ERROR_UPLOADING_FILE = 'Error uploading file',
  FILE_DELETED_SUCCESSFULLY = 'File deleted successfully',
  ERROR_DELETING_FILE = 'Error deleting file',
  FILE_URL_GENERATED_SUCCESSFULLY = 'File URL generated successfully',
  ERROR_GENERATING_FILE_URL = 'Error generating file URL',
  NO_FILE_DELETED = 'No file deleted',
  ALL_FILES_DELETED = 'All files deleted',
  ERROR_DELETING_FILES = 'Error deleting files',
  FILE_ALREADY_EXISTS = 'File already exists',
}
