export enum TEAM_RESPONSE {
  TEAM_NOT_FOUND = 'Team not found',
  TEAMS_NOT_FOUND = 'Teams not found',
  TEAM_NOT_FOUND_BY_ID = 'Team not found by id',
  TEAM_NOT_FOUND_BY_USER = 'Team not found by user',
  TEAM_NOT_FOUND_BY_USER_AND_ID = 'The user of the team and the logged in user do not match',
  TEAM_FAILED_SAVE = 'Could not save team, please try again',
  TEAM_FAILED_DELETED = 'Could not deleted team, please try again',
  TEAM_FAILED_UPDATE = 'Could not updated team, please try again',
  TEAM_DELETED = 'Team deleted',
  TEAM_UPDATED = 'Team updated',
  TEAM_CREATED = 'Team created',
  TEAMS_FOUND_BY_USER = 'Teams found by user',
  TEAM_FOUND_BY_ID = 'Team found by id',
}
