name: CI Workflow

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['*']

jobs:
  run-tests:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Load environment variables from .env.dist
        run: |
          cp .env.dist .env
          echo "NODE_ENV=development" >> .env
        env:
          NODE_ENV: development

      - name: NPM or Yarn install with caching
        uses: bahmutov/npm-install@v1.6.0

      - name: Build
        run: |
          npm run lint
          npm run format
          npm run build
          npm run test:cov
